### ISSUE TITLE
Documnet Modal file is missing 

### ISSUE THREAD

**Issue by sheikhsuleman123** [Snehasis4321/todo_app_appwrite#1]
I am unable to find the document.dart  modal file

**Comment by Snehasis4321** [comment]
I have not written any document.dart file , 
I have use Document Model which is a part of appwrite .     
`import 'package:appwrite/models.dart';` 
import this package will solve you error.

**Comment by sheikhsuleman123** [comment]
In your video you show this document where I can see this file in my
project folder ?

**Comment by Snehasis4321** [comment]
paste the screenshot here. i will try to figure whats your problem.

**Comment by sheikhsuleman123** [comment]
![image](https://github.com/Snehasis4321/todo_app_appwrite/assets/37480028/a8ca76a3-b52f-4e6a-ba87-04ea72ba70d4)


i am unable to import this

**Comment by Snehasis4321** [comment]
Line 11 final client= Client(); is wrong             

till will be something like this 

`Client client = Client()
    .setEndpoint('YOUR_APPWRITE_ENDPOINT')   //Replace with your appwrite endpoin
    .setProject('YOUR_PROJECT_ID')                     //Replace with your projectID
    .setSelfSigned(
        status: true); `

## In my case i have imported it from auth.dart 
![image](https://github.com/Snehasis4321/todo_app_appwrite/assets/96995340/8e719654-429d-4130-99d2-a5f8ea53738a)
![image](https://github.com/Snehasis4321/todo_app_appwrite/assets/96995340/1ccad07e-6dd0-441f-81fa-b9fcae428420)

## I hope you got it.

**Comment by sheikhsuleman123** [comment]
Dear Brother I am using the Getx   and this is my code I get an error from Appwrite 

![image](https://github.com/Snehasis4321/todo_app_appwrite/assets/37480028/03494ea2-46f3-4423-bd89-334aad4a0459)

**Comment by Snehasis4321** [comment]
look like a backend error, just check and verify all the endpoints and project id are correct according to appwrite console.

**Comment by sheikhsuleman123** [comment]
login and signup functionality is working ok but I am facing error in the database only , is there any solution or suggestion for this

**Comment by Snehasis4321** [comment]
I will suggest you check the permissions of your database collection in you appwrite console,are READ WRITE permission are given or not.

**Comment by sheikhsuleman123** [comment]
Brother I cross-check everything login signup is working perfectly now when I add the todo also same error occur 

![image](https://github.com/Snehasis4321/todo_app_appwrite/assets/37480028/56a34c4e-0cd1-4319-8df9-df3c2cb8f568)

**Comment by sheikhsuleman123** [comment]
solved
 I am proceeding your videos next If I have any issue can I ask you ?
